/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedBackupsRouteImport } from './routes/_authed/backups'
import { Route as AuthedRequestsRouteImport } from './routes/_authed/requests'
import { Route as AuthedJobsIndexRouteImport } from './routes/_authed/jobs/index'
import { Route as AuthedJobsIdRouteImport } from './routes/_authed/jobs/$id'
import { Route as AuthedUsersIndexRouteImport } from './routes/_authed/users/index'
import { Route as AuthedUsersIdRouteImport } from './routes/_authed/users/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsRoute = AuthedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIndexRoute = AuthedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsIdRoute = AuthedJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIndexRoute = AuthedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersIdRoute = AuthedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/backups': typeof AuthedBackupsRoute
  '/requests': typeof AuthedRequestsRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/jobs/': typeof AuthedJobsIndexRoute
  '/users/': typeof AuthedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/backups': typeof AuthedBackupsRoute
  '/requests': typeof AuthedRequestsRoute
  '/': typeof AuthedIndexRoute
  '/jobs/$id': typeof AuthedJobsIdRoute
  '/users/$id': typeof AuthedUsersIdRoute
  '/jobs': typeof AuthedJobsIndexRoute
  '/users': typeof AuthedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/backups': typeof AuthedBackupsRoute
  '/_authed/requests': typeof AuthedRequestsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/jobs/$id': typeof AuthedJobsIdRoute
  '/_authed/users/$id': typeof AuthedUsersIdRoute
  '/_authed/jobs/': typeof AuthedJobsIndexRoute
  '/_authed/users/': typeof AuthedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/backups'
    | '/requests'
    | '/jobs/$id'
    | '/users/$id'
    | '/jobs/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/backups'
    | '/requests'
    | '/'
    | '/jobs/$id'
    | '/users/$id'
    | '/jobs'
    | '/users'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/backups'
    | '/_authed/requests'
    | '/_authed/'
    | '/_authed/jobs/$id'
    | '/_authed/users/$id'
    | '/_authed/jobs/'
    | '/_authed/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups': {
      id: '/_authed/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthedBackupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/': {
      id: '/_authed/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthedJobsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs/$id': {
      id: '/_authed/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof AuthedJobsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/': {
      id: '/_authed/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedUsersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users/$id': {
      id: '/_authed/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthedUsersIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBackupsRoute: typeof AuthedBackupsRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedJobsIdRoute: typeof AuthedJobsIdRoute
  AuthedUsersIdRoute: typeof AuthedUsersIdRoute
  AuthedJobsIndexRoute: typeof AuthedJobsIndexRoute
  AuthedUsersIndexRoute: typeof AuthedUsersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBackupsRoute: AuthedBackupsRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedJobsIdRoute: AuthedJobsIdRoute,
  AuthedUsersIdRoute: AuthedUsersIdRoute,
  AuthedJobsIndexRoute: AuthedJobsIndexRoute,
  AuthedUsersIndexRoute: AuthedUsersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
