/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as GrowthStatisticsRouteImport } from './routes/growth-statistics'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as RegionalRankingsRouteImport } from './routes/regional-rankings'
import { Route as RegionalStatisticsRouteImport } from './routes/regional-statistics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthStatisticsRoute = GrowthStatisticsRouteImport.update({
  id: '/growth-statistics',
  path: '/growth-statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalRankingsRoute = RegionalRankingsRouteImport.update({
  id: '/regional-rankings',
  path: '/regional-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalStatisticsRoute = RegionalStatisticsRouteImport.update({
  id: '/regional-statistics',
  path: '/regional-statistics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/growth-statistics': typeof GrowthStatisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/regional-rankings': typeof RegionalRankingsRoute
  '/regional-statistics': typeof RegionalStatisticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/growth-statistics': typeof GrowthStatisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/regional-rankings': typeof RegionalRankingsRoute
  '/regional-statistics': typeof RegionalStatisticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/growth-statistics': typeof GrowthStatisticsRoute
  '/maintenance': typeof MaintenanceRoute
  '/regional-rankings': typeof RegionalRankingsRoute
  '/regional-statistics': typeof RegionalStatisticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/growth-statistics'
    | '/maintenance'
    | '/regional-rankings'
    | '/regional-statistics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/growth-statistics'
    | '/maintenance'
    | '/regional-rankings'
    | '/regional-statistics'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/growth-statistics'
    | '/maintenance'
    | '/regional-rankings'
    | '/regional-statistics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  GrowthStatisticsRoute: typeof GrowthStatisticsRoute
  MaintenanceRoute: typeof MaintenanceRoute
  RegionalRankingsRoute: typeof RegionalRankingsRoute
  RegionalStatisticsRoute: typeof RegionalStatisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth-statistics': {
      id: '/growth-statistics'
      path: '/growth-statistics'
      fullPath: '/growth-statistics'
      preLoaderRoute: typeof GrowthStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-rankings': {
      id: '/regional-rankings'
      path: '/regional-rankings'
      fullPath: '/regional-rankings'
      preLoaderRoute: typeof RegionalRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regional-statistics': {
      id: '/regional-statistics'
      path: '/regional-statistics'
      fullPath: '/regional-statistics'
      preLoaderRoute: typeof RegionalStatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  GrowthStatisticsRoute: GrowthStatisticsRoute,
  MaintenanceRoute: MaintenanceRoute,
  RegionalRankingsRoute: RegionalRankingsRoute,
  RegionalStatisticsRoute: RegionalStatisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
