import { ApiError, NetworkError, type Snapshot } from "@pca/shared"
import { Link } from "@tanstack/react-router"
import type { ReactNode } from "react"

import { Layout } from "../Layout"

export interface Tab<T extends string> {
  id: T
  label: string
}

interface StatisticsPageProps<T extends string> {
  title: string
  description: string
  tabs: readonly Tab<T>[]
  activeTab: T
  onTabChange: (tab: T) => void
  children: ReactNode
}

export function StatisticsPage<T extends string>({ title, description, tabs, activeTab, onTabChange, children }: StatisticsPageProps<T>) {
  return (
    <Layout className="statistics-site">
      <div className="statistics-page max-w-1340 mx-auto px-4 sm:px-6">
        <nav className="statistics-section-nav" aria-label="Statistics pages">
          <Link to="/regional-statistics" activeProps={{ className: "active" }}>
            Regional Statistics
          </Link>
          <Link to="/growth-statistics" activeProps={{ className: "active" }}>
            Growth Statistics
          </Link>
        </nav>

        <header className="statistics-heading">
          <span className="statistics-eyebrow">Philippine cubing by region</span>
          <h1>{title}</h1>
          <p>{description}</p>
        </header>

        <nav className="statistics-tabs" aria-label={`${title} views`}>
          {tabs.map(tab => (
            <button
              key={tab.id}
              type="button"
              className={activeTab === tab.id ? "active" : ""}
              aria-current={activeTab === tab.id ? "page" : undefined}
              onClick={() => onTabChange(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </nav>

        {children}
      </div>
    </Layout>
  )
}

export function apiErrorMessage(error: unknown) {
  if (error instanceof ApiError) {
    if (error.status === 503) {
      return "The prepared statistics are not available yet. The latest data needs to be generated by the backend first."
    }
    if (error.status === 404) return error.detail || "No statistics were found for this selection."
    if (error.detail) return error.detail
  }
  if (error instanceof NetworkError) {
    return "The statistics server could not be reached. Check that the local backend is running, then try again."
  }
  return "The statistics could not be loaded. Please try again."
}

export function StatisticsStatus({ isLoading, error, onRetry }: { isLoading: boolean; error: unknown; onRetry: () => void }) {
  if (isLoading) {
    return (
      <div className="statistics-status" role="status" aria-live="polite">
        <span className="statistics-loader" aria-hidden="true" />
        <div>
          <strong>Loading statistics</strong>
          <p>Reading the latest prepared results.</p>
        </div>
      </div>
    )
  }
  if (error) {
    return (
      <div className="statistics-status statistics-status-error" role="alert">
        <div>
          <strong>We couldn&apos;t show these statistics.</strong>
          <p>{apiErrorMessage(error)}</p>
        </div>
        <button type="button" onClick={onRetry}>
          Try again
        </button>
      </div>
    )
  }
  return null
}

export function Methodology({ children }: { children: ReactNode }) {
  return (
    <aside className="statistics-methodology" aria-label="How this is calculated">
      <strong>How this is calculated</strong>
      <p>{children}</p>
    </aside>
  )
}

export function SnapshotNote({ snapshot, showPreviewWarning = false }: { snapshot?: Snapshot; showPreviewWarning?: boolean }) {
  if (!snapshot) return null
  const isPreview = /preview/i.test(snapshot.export_version || "")
  return (
    <>
      {showPreviewWarning && isPreview && (
        <aside className="statistics-preview-warning" role="alert">
          <strong>Local preview data</strong>
          <p>
            The competitor home-region assignments in this snapshot are synthetic and are only here for layout testing.
            Do not interpret these regional scores or placements as real results.
          </p>
        </aside>
      )}
      <p className="statistics-snapshot">
        Prepared from WCA export <strong>{snapshot.export_version}</strong>
        {snapshot.latest_year ? ` · Through ${snapshot.latest_year}` : ""}
      </p>
    </>
  )
}
